#!/bin/sh

# Automatically moving the correct file for you, assuming default installation
# Assume if not Mac OS X, then Windows (No love for Linux)
if 	[[ `uname` == "Darwin" ]]; then
	cp settings.json ~/Library/Application\ Support/Code/User/settings.json
	cp keybindings.json.mac ~/Library/Application\ Support/Code/User/keybindings.json
fi

# Theme
code --install-extension monokai.theme-monokai-pro-vscode

# Languages
code --install-extension ms-python.python
