#!/bin/sh

# First cp zprofile (required by brew)
cp ~/dev/setup/Terminal/.zprofile ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Then cp zshrc
cp ~/dev/setup/Terminal/.zshrc ~/.zshrc

# Auto-install things for Mac
if [[ `uname` == "Darwin" ]]; then
	brew install fnm pyenv starship zsh-completions
fi

# Source and reload zsh
source ~/.zshrc
