#!/bin/sh

# First cp zprofile (required by brew)
cp ~/dev/setup/Terminal/.zprofile ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Then cp zshrc
cp ~/dev/setup/Terminal/.zshrc ~/.zshrc

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

# Auto-install things for Mac
if [[ `uname` == "Darwin" ]]; then
	brew install pyenv starship zsh-completions
	nvm install --lts
fi

# Source and reload zsh
source ~/.zshrc
