#!/bin/sh

# Auto-install things for Mac
if [[ `uname` == "Darwin" ]]; then
    # Install uv
    curl -LsSf https://astral.sh/uv/install.sh | sh

	# Install rest
    brew install direnv fnm starship zsh-completions
fi
