[username]
style_user = "bold purple"
format = "[$user]($style) "
show_always = true

[hostname]
style = "bold yellow"
ssh_only = false

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[✗ ](bold red)"

[container]
format = '[$symbol \[$name\]]($style) '

[directory]
style = "bold cyan"
truncation_length = 0

[python]
python_binary = "python3"
detect_extensions = ["py"]
detect_files = ["requirements.txt", "pyproject.toml"]
